### ISSUE TITLE
API for programatically move files and directories or to listen for such events

### ISSUE THREAD

**Issue by felipenmoura** [fabiomcosta/mvjs#5]
If we had an API, we could, for example, run a command that "fixes" the paths for the files that have just been moved.
For example, if I have a webpack watching files, when moved a file, it could notice the change in the tree and allow me to use this API to adjust the files within the project.

**Comment by fabiomcosta** [comment]
Hi @felipenmoura !
I see... great suggestion!
We could expose the `moveModules` (actually move modules) and `updateModules` (calls the codemod on modules) functions as the API.

**Comment by felipenmoura** [comment]
Nice, that would be great!

**Comment by fabiomcosta** [comment]
@felipenmoura I actually changed the API names to `transform` and `move`, but they do what you would expect.

**Comment by fabiomcosta** [comment]
`move` and `transform` are available on v1.6.0 and there is documentation on the README.
Thank you for the suggestion! Let me know what you think and if you find any issues!

**Comment by felipenmoura** [comment]
awesome!
I'will soon give it a try :)
